# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d39aa54d2f5ef35e1676c8572262dfcfe6c28085b205785f750898da0ae60c0d8e7bda725a83a45763ef27c8308a9a021e307f82733aae11be4788f4a30b339

test:
  secret_key_base: 6d867b32763241b8594cfde27477094be6ce721f7b4115dcb4de55cfd1ea6b377be2885b0dbb8631ad224187406626fd37e4f617f8faa58dbe22f47d61051c49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
